matrix:
  NAME:
    - ukhomeofficedigital/lev-report
  DOCKER_USERNAME:
    - ukhomeofficedigital+lev_report
  DOCKER_REPO:
    - quay.io

pipeline:
  test_pr:
    image: quay.io/ukhomeofficedigital/lev-ci
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - make test
    when:
      event: pull_request
  test_push:
    image: quay.io/ukhomeofficedigital/lev-ci
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - set -o pipefail
      - make test | tee 'test.log'
      - set-tags
    when:
      event: push
      branch: master

  docker-build-and-push:
    image: ukhomeoffice/drone-docker
    secrets: [ docker_password ]
    username: '${DOCKER_USERNAME}'
    repo: '${DOCKER_REPO}/${NAME}'
    registry: '${DOCKER_REPO}'
    when:
      event: push
      branch: master

  deploy_image:
    image: quay.io/ukhomeofficedigital/lev-ci
    secrets:
      - KUBE_SERVER
      - KUBE_NAMESPACE
      - KUBE_TOKEN
      - KUBE_DEPLOYMENT
      - KUBE_CONTAINER
    environment:
      - DOCKER_REPO=quay.io
      - DOCKER_BASEDIR=/ukhomeofficedigital/
      - DOCKER_IMAGE=lev-report
    commands:
      - PACKAGE_VERSION=`cat .tags | awk -F "," '{ print $2 }'`
      - TAG="v$${PACKAGE_VERSION}-$${DRONE_BUILD_NUMBER}-$${DRONE_COMMIT}"
      - IMAGE="$${DOCKER_REPO}$${DOCKER_BASEDIR}$${DOCKER_IMAGE}"
      - kubectl="kubectl --insecure-skip-tls-verify --server=$${KUBE_SERVER} --namespace=$${KUBE_NAMESPACE} --token=$${KUBE_TOKEN}"
      - $${kubectl} scale deployment $${KUBE_DEPLOYMENT} --replicas 2
      - $${kubectl} set image deployment/$${KUBE_DEPLOYMENT} "$${KUBE_CONTAINER}=$${IMAGE}:$${TAG}"
      - $${kubectl} rollout status deployment/$${KUBE_DEPLOYMENT}
      - $${kubectl} scale deployment $${KUBE_DEPLOYMENT} --replicas 1
    when:
      branch: master
      event: push
